from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os


# ===============================
# DISPLAY NAME (ENGLISH FOR PDF)
# ===============================

DISPLAY_NAME = {
    "Energi (kkal)": "Energi (kkal)",
    "Karbo (g)": "Karbohidrat (g)",
    "Lemak (g)": "Lemak (g)",
    "Protein (g)": "Protein (g)",
    "Kalsium (mg)": "Kalsium (mg)",
    "Vit A (RE)": "Vitamin A (RE)",
    "Vit C (mg)": "Vitamin C (mg)",
    "Vit E (mcg)": "Vitamin E (mcg)",
    "Zinc (mg)": "Zinc (mg)",
    "Zat Besi (mg)": "Zat Besi (mg)"
}


# ===============================
# MAIN REPORT FUNCTION
# ===============================

def build_pdf_report(child_info, nutrisi, akg_percent, recommendations=None):

    os.makedirs("reports", exist_ok=True)

    fname = f"reports/sende_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    c = canvas.Canvas(fname, pagesize=A4)
    w, h = A4

    y = h - 50

    # =====================
    # HEADER
    # =====================

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "SENDE — Laporan Analisis Gizi")
    y -= 25

    c.setFont("Helvetica", 10)
    c.drawString(50, y, datetime.now().strftime("%d %B %Y %H:%M"))
    y -= 30

    # =====================
    # CHILD INFORMATION
    # =====================

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Child Information")
    y -= 20

    c.setFont("Helvetica", 10)

    if isinstance(child_info, dict):
        c.drawString(60, y, f"Name: {child_info.get('name','-')}")
        y -= 15
        c.drawString(60, y, f"Age: {child_info.get('age_months','-')} months")
        y -= 15
        c.drawString(60, y, f"Sex: {child_info.get('sex','-')}")
        y -= 15
        c.drawString(60, y, f"Weight: {child_info.get('weight','-')} kg")
        y -= 15
        c.drawString(60, y, f"Height: {child_info.get('height','-')} cm")
        y -= 15
    else:
        c.drawString(60, y, str(child_info))
        y -= 15

    y -= 15

    # =====================
    # NUTRIENT ESTIMATION
    # =====================

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Perkiraan Kandungan Gizi (Per Porsi)")
    y -= 20

    c.setFont("Helvetica", 10)

    for k, v in nutrisi.items():
        label = DISPLAY_NAME.get(k, k)
        c.drawString(60, y, f"{label}: {v}")
        y -= 15

        if y < 80:
            c.showPage()
            y = h - 60
            c.setFont("Helvetica", 10)

    y -= 15

    # =====================
    # AKG PERCENT
    # =====================

    if akg_percent:

        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "AKG Coverage per Portion (%)")
        y -= 20

        c.setFont("Helvetica", 10)

        for k, v in akg_percent.items():
            label = DISPLAY_NAME.get(k, k)
            c.drawString(60, y, f"{label}: {round(v,1)} %")
            y -= 15

            if y < 80:
                c.showPage()
                y = h - 60
                c.setFont("Helvetica", 10)

        y -= 15

    # =====================
    # RECOMMENDATIONS
    # =====================

    if recommendations:

        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Rekomendasi Gizi Personal")
        y -= 20

        c.setFont("Helvetica", 10)

        for r in recommendations:

            # wrap text manual
            line = f"- {r}"
            max_len = 90

            while len(line) > max_len:
                c.drawString(60, y, line[:max_len])
                line = line[max_len:]
                y -= 15

                if y < 80:
                    c.showPage()
                    y = h - 60
                    c.setFont("Helvetica", 10)

            c.drawString(60, y, line)
            y -= 15

            if y < 80:
                c.showPage()
                y = h - 60
                c.setFont("Helvetica", 10)

    # =====================
    # FOOTER
    # =====================

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(
        50,
        40,
        "Generated by SENDE — Human-Centered Multimodal Nutrition Decision Support"
    )

    c.save()

    return fname
